name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Make deploy script executable
        run: chmod +x deploy.sh

      - name: Run Deployment
        run: ./deploy.sh
